# Generated by Django 4.1.7 on 2023-03-08 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('icon', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('merchant', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedTransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budginator.budget')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budginator.trackedtransaction')),
            ],
        ),
    ]
