# Generated by Django 4.1.7 on 2023-03-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budginator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='icon',
            field=models.CharField(max_length=4),
        ),
    ]
