# Generated by Django 4.1.7 on 2023-03-10 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budginator', '0003_budget_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('multiplier', models.IntegerField(choices=[(-1, 'Debits'), (1, 'Credits')])),
            ],
        ),
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('merchant', models.CharField(max_length=255)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budginator.bankaccount')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budginator.trackedtransaction')),
            ],
        ),
    ]
