# Generated by Django 4.1.7 on 2023-03-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budginator', '0004_bankaccount_importedtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='multiplier',
            field=models.IntegerField(choices=[(-1, 'Debits'), (1, 'Credits')], verbose_name='Positive Numbers Are'),
        ),
    ]
