# Generated by Django 4.2.24 on 2025-09-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budginator', '0006_alter_importedtransaction_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedtransaction',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported', to='budginator.trackedtransaction'),
        ),
        migrations.CreateModel(
            name='AutoLinkExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budginator.budget')),
            ],
        ),
    ]
